### ISSUE TITLE
TypeError with tangods-limaccds-1.5.5

### ISSUE THREAD

**Issue by julianofjm** [MaxIV-KitsControls/app-maxiv-beamviewer#2]
After tangods-limaccds update to version 1.5.5 the beamviewer keeps throwing the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tgconf_beamviewer/panels/limabeam.py", line 480, in handle_calibration
    xoffset, yoffset = self._get_offset()
  File "/usr/lib/python2.7/site-packages/tgconf_beamviewer/panels/limabeam.py", line 465, in _get_offset
    rx, ry = ruler["pos"]
TypeError: list indices must be integers, not str
```

**Comment by 13bscsaamjad** [comment]
taurusgui for beamviewer plugin in limaccds expects a string for ruler, the update in the tango-limaccds fixed that but broke beamviewer gui.
